watch_stylesheet: true
watch_config: true

bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: false
      acrylic: true
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_taskbar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "current_user",
          # "power_button",
          "komorebi_workspaces", 
          "komorebi_active_layout",
          "active_window",
          # "media_player",
        ]
      center: ["clock"]
      right:
        [
          # "tray_button",
          "weather",
          "cpu",
          "memory",
          # "disk",
          "volume",
          "wifi",
          "battery",
          "search_button",
          "notification_button"
        ]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: "Desktop"
      max_length: 56
      max_length_ellipsis: ".."
      monitor_exclusive: false

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon}  {percent}%"
      label_alt: "{icon}  {percent}% | time: {time_remaining}"
      time_remaining_natural: false

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "\udb82\udd54  {%a %I:%M %p}"
      label_alt: "\udb82\udd54  {%A %d %B %Y %I:%M %p}"
      timezones: ["Asia/Kolkata"]
      callbacks:
        on_right: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\udb80\udf5b {info[percent][total]}%"
      label_alt: "\udb80\udf5b {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\uf200  {virtual_mem_percent}%"
      label_alt: "\uf200  {virtual_mem_free}"
      update_interval: 2000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{name}"
        label_default_name: "{index}"
        label_zero_index: false
        preview_workspace: true
        hide_empty_workspaces: false
      
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon}"
      label_alt: "{wifi_icon}  {wifi_name}"
      update_interval: 5000
      wifi_icons:
        - "\udb82\udd2e" # 0% strength (no wifi)
        - "\udb82\udd1f" # 1-25% strength
        - "\udb82\udd22" # 26-50% strength
        - "\udb82\udd25" # 51-75% strength
        - "\udb82\udd28" # 76-100% strength. Alternate theming: \uf1eb
      callbacks:
        on_left: "exec autohotkey64 C:/Users/Ashwin/.dotfiles/.config/yasb/functions/action-widget.ahk"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:network"

  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "\udb80\udeca {volume_label}{space[used][percent]:.1f}%"
      label_alt: "\udb80\udeca {volume_label}{space[used][gb]:.1f}GB / {space[total][gb]:.1f}GB"
      volume_label: "C:"
      update_interval: 60000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:disksandvolumes"
  
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{volume_icon}  {volume_level}"
      label_alt: "{volume_icon}  {volume_level}"
      update_interval: 100
      volume_icons: 
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0% volume
        - "\uf027"  # Icon for 1-25% volume
        - "\uf027"  # Icon for 26-50% volume
        - "\uf028"  # Icon for 51-75% volume
        - "\uf028"  # Icon for 76-100% volume
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:sound"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\ueb01 \ueab4 {download_speed} | \ueab7 {upload_speed}"
      label_alt: "\ueb01 \ueab4 {upload_speed} | \ueab7 {download_speed}"
      update_interval: 1000 # Update interval should be a multiple of 1000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        grid: "[G]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  media_player:
      type: "yasb.media_player.MediaPlayerWidget"
      options:
        label: "{media[title]} - {media[artist]}"
        label_alt: "{media[title]} - {media[artist]}"
        update_interval: 500
        keep_thumbnail_aspect_ratio: false
        layout: ["thumbnail", "label", "prev", "play_pause", "next"]
        icons:
          shuffle: "\uf074"
          play: "\uf04b"
          pause: "\uf04c"
          next: "\uf051"
          prev: "\uf048"
          close: "\uf00d"
          repeat_off: "\uf2f9"
          repeat_track: "\uf2f9 (T)"
          repeat_list: "\uf2f9 (L)"

  power_button:
    type: "yasb.power_button.PowerButtonWidget"
    options:
      label: "\ue62a"
      layout: ["lock", "restart", "shutDown"]

  # Some custom widgets
  current_user:
    type: "yasb.custom.CustomWidget"
    options:
      label: "{data}"
      label_alt: "{data}"
      class_name: "current-user-widget"
      exec_options:
        run_cmd: "echo %username%"
        return_format: "string"
      callbacks:
        on_right: "toggle_label"

  explorer_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf07c"
      label_alt: "Explorer"
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: "toggle_label"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf3c5 {data[city]}, {data[region]}"
      label_alt: "\uf3c5 {data[ip]} [{data[country]}]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                        # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2  {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2  {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe wttr.in/Nashik?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"
  
  lang:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udb80\udf0c {data}"
      label_alt: "\udb81\udfd3 {data}"
      class_name: "lang-widget"
      exec_options:
        run_cmd: "powershell add-type -assemblyname system.windows.forms;([system.windows.forms.inputlanguage]::currentinputlanguage).Culture.Name"
        # run every 3 sec
        run_interval: 3000
        return_format: "string"

  notification_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0f3"
      label_alt: "\uf49a"
      class_name: "notification-widget"
      callbacks:
        on_left: "exec autohotkey64 C:/Users/Ashwin/.dotfiles/.config/yasb/functions/notification-widget.ahk"
        on_right: "toggle_label"

  start_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a Start"
      class_name: "start-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec autohotkey64 C:/Users/Ashwin/.dotfiles/.config/yasb/functions/start-widget.ahk"
        on_right: "toggle_label"

  search_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf422"
      label_alt: "\uf422 Search"
      class_name: "search-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec autohotkey64 C:/Users/Ashwin/.dotfiles/.config/yasb/functions/search-widget.ahk"
        on_right: "toggle_label"

  tray_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf107"
      label_alt: "\uf107"
      class_name: "tray-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec autohotkey64 C:/Users/Ashwin/.dotfiles/.config/yasb/functions/tray-widget.ahk"
        on_right: "toggle_label" 
