import = [
  "C:\\Users\\Ashwin\\AppData\\Local\\npm-cache\\_npx\\808b709e6234a442\\node_modules\\alacritty-themes\\themes\\Tokyonight_Night.toml"
]

[shell]
program = "C:\\Users\\Ashwin\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe"
args = ["-wd ~"]

[window]
dynamic_title = false
opacity = 0.5
  [window.padding]
  x = 7
  y = 7

[font]
size = 12
  [font.normal]
  family = "JetBrainsMono NFP"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono NFP"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono NFP"
  style = "Italic"
